version: 2.1

executors:
  worker:
    docker:
      - image: circleci/node
    working_directory: ~/ci

jobs:
  install:
    executor: worker
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - persist_to_workspace:
          root: ~/ci
          paths: node_modules

  lint:
    executor: worker
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci
      - run:
          name: lint
          command: npm run lint

  build:
    executor: worker
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ~/ci
          paths: .

  test:
    executor: worker
    steps:
      - checkout
      - attach_workspace:
          at: ~/ci
      - run:
          name: test
          command: npm test

  publish:
    executor: worker
    steps:
      - attach_workspace:
          at: ~/ci
      - run:
          name: login
          command: npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
      - run:
          name: publish
          command: npm publish

workflows:
  version: 2
  ci:
    jobs:
      - install:
          filters:
              tags:
                only: /.*/
      - lint:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - install
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - install
            - build
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - lint
            - build
            - test
          context: npm token
          filters:
            tags:
              only: /^v[0-9].*/
            branches:
              ignore: /.*/
